### ISSUE TITLE
Replace travis CI with github actions CI

### ISSUE THREAD

**Issue by chengfang** [arquillian/arquillian-extension-jacoco#100]
##### Issue Overview

Current travis-ci can become unresponsive at times, and cannot provide reliable test results for PRs.

github actions offer a CI experience more integrated with the current development workflow.

If you have any comments and thoughts, feel free to share and start the discussion.

**Comment by chengfang** [comment]
https://github.com/arquillian/arquillian-extension-jacoco/pull/101 replaces travis with circleci.

@bartoszmajsak thoughts on circleci vs github actions?

**Comment by bartoszmajsak** [comment]
They're quite similar in capabilities we need. I don't really have strong preference. We've switched to Circle from Travis quite some time ago for the most active repos and back then GH actions were not what they're today.

I've noticed the PR being merged without a build ran so I quickly provided set-up without realizing there's an issue mentioning GH actions opened.

**Comment by chengfang** [comment]
I see. Since we now have circleci in place, I'm closing this issue.
