### ISSUE TITLE
Evaluation of includes and excludes needs trimming

### ISSUE THREAD

**Issue by moldowan** [arquillian/arquillian-extension-jacoco#22]
JacocoConfiguration already splits multiple includes/excludes in a whitespace aware way using delimiter `"\\s*;\\s*"`. But this only strips the whitespaces around the delimiter, _not_ whitespaces before the first and after the last entry.
Because of this you cannot use newlines to format the entries.

**Comment by bartoszmajsak** [comment]
Thanks @moldowan for reporting. It's fixed upstream
