### ISSUE TITLE
Please add more info to the README

### ISSUE THREAD

**Issue by CSchulz** [arquillian/arquillian-extension-jacoco#24]
In special it would be nice to have some information how to use it with surefire and failsafe plugins. These both plugins are typical setup in maven projects.

**Comment by famod** [comment]
PR #73 will add a link to https://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html

cc: @bartoszmajsak

**Comment by famod** [comment]
@bartoszmajsak I think this issue can be closed now after the merge of #73.
