### ISSUE TITLE
1.0.0.Alpha10 is almost like an invisible ninja release

### ISSUE THREAD

**Issue by famod** [arquillian/arquillian-extension-jacoco#50]
In contrast to 1.0.0.Alpha9 and below:
- there is no tag  in this repo
- there is also [no site update](http://arquillian.org/modules/jacoco-extension/) or [blog entry](http://arquillian.org/blog/tags/jacoco/)

There also isn't a "Releases" section in this repo.

All this makes it hard to keep track of updates.

**Comment by bartoszmajsak** [comment]
LOL for the "ninja release" and you are right, somewhere that got lost. Should be fine now. Thanks for spotting and reporting the issue.

As for the website update - I'm investigating.

**Comment by famod** [comment]
Thanks for your quick reaction!
