### ISSUE TITLE
Extension is not usable for old servers that depend on ASM 3

### ISSUE THREAD

**Issue by famod** [arquillian/arquillian-extension-jacoco#72]
##### Issue Overview
You cannot use this extension with old stacks/servers that use ASM 3 (like JBoss EAP 6.4 which bundles CXF 2.7).
With `appendAsmLibrary=true` (default), CXF will choke because it expects ASM 3, not 7.
With `appendAsmLibrary=false`, CXF will work but the extension will fail because JaCoCo requires ASM 7, not 3.

##### Expected Behaviour
It should be possible to use this extension with older servers.

##### Current Behaviour
Either some server functionality or the extension breaks. Most likely, you will see deployment exceptions or even very low-level errors like `StackOverflowError`.

##### Steps To Reproduce
1. take an old server like JBoss EAP 6.4
2. try to use the extension

##### Additional Information
For years, I have been using `maven-shade-plugin` to create `jacoco-core` and `arquillian-extension-jacoco` packages with a "private"/relocated ASM/JaCoCo.
I really think this extension should provide an alternate package/jar with does not require the users to fiddle around with `maven-shade-plugin` themselves.

**Comment by famod** [comment]
Btw, this is not an entirely new problem and has been discussed before, see: #25

**Comment by famod** [comment]
I've come pretty far with that locally but I've hit a `maven-shade-plugin` problem: https://issues.apache.org/jira/browse/MSHADE-311
I already found a solution for that and I am going create a PR for that as well, but I don't know whether this will be merged and when a new `maven-shade-plugin` will be available.

In the meantime I will most likely create a draft PR so we can discuss my approach.

cc: @bartoszmajsak

**Comment by famod** [comment]
FYI: PR for the `maven-shade-plugin` problem: https://github.com/apache/maven-shade-plugin/pull/35

**Comment by famod** [comment]
My PR was merged. Thanks, @bartoszmajsak!
 Any plans to cut a release?

**Comment by bartoszmajsak** [comment]
Sure, doing it later today. Thanks for your work!

**Comment by bartoszmajsak** [comment]
I guess we can close that now?

**Comment by famod** [comment]
> I guess we can close that now?

Sure!

**Comment by bartoszmajsak** [comment]
@famod we are hitting an issue with the new module: https://issues.sonatype.org/browse/OSSRH-3723 which is blocking the release. Shall we create dummy jars as suggested in this issue? Can't really think of anything better ATM :)

**Comment by famod** [comment]
That's ... unfortunate. Which modules are affected? Only `arquillian-jacoco-with-asm` or also the parent? I guess `arquillian-jacoco` is fine?

**Comment by bartoszmajsak** [comment]
@famod I think for now we can simply stick to the workaround. How about creating a class named `AboutThisModule` with an explanation?

**Comment by famod** [comment]
Worth a try. Or a README.md in src/main/resources. Shall I have a look at it?

**Comment by bartoszmajsak** [comment]
Just `README.md` might result in no javadoc jar error :) I will take care of it, thanks.

**Comment by bartoszmajsak** [comment]
@famod found a better way at the end of the day https://github.com/arquillian/arquillian-extension-jacoco/commit/fda5d2611cac1711cffdd5bfdd11866e98a7af15#diff-3115f8297ee3c957b32b8decc77fd043R47-R48
